version: "3.8"

services:
  socialnetwork:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - path: ./.env
        required: true
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialnetwork
  cache:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: redis
