#prettier-ignore
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
data:
  postgresql-password: {{ .Values.secret.password }}
  repmgr-password: {{ .Values.secret.repmgr_password }}
  postgres-username: {{ .Values.secret.user }}
  postgres-database: {{ .Values.secret.db }}
