apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
data:
    POSTGRES_DB : {{ .Values.secret.db }}
    POSTGRES_USER: {{ .Values.secret.user }}
    POSTGRES_PASSWORD: {{ .Values.secret.password }}
    SECRET_KEY: {{ .Values.secret.secret_key }}
