#prettier-ignore
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  access_key_id: {{ .Values.secret.aws_access_key }}
  secret_access_key: {{ .Values.secret.aws_secret_key }}
